package za.ac.cput.Service.impl;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;
import za.ac.cput.domain.JobSeeker;
import za.ac.cput.factory.JobSeekerFactory;
import za.ac.cput.repository.IJobSeekerRepository;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@Transactional
class JobSeekerServiceImplTest {

    @Autowired
    private JobSeekerServiceImpl jobSeekerService;

    @Autowired
    private IJobSeekerRepository jobSeekerRepository;

    @BeforeEach
    void setUp() {
        jobSeekerRepository.deleteAll();
    }

    private JobSeeker createTestJobSeeker() {
        return JobSeekerFactory.createJobSeeker(
                "test" + System.currentTimeMillis() + "@gmail.com",
                "securePassword123",
                "Test",
                "User",
                "0712345678",
                "Cape Town",
                "Java Software Engineer",
                "Passionate backend developer with 5 years of experience"
        );
    }

    @Test
    @Order(1)
    void create() {
        JobSeeker jobSeeker = createTestJobSeeker();
        assertNotNull(jobSeeker);

        JobSeeker created = jobSeekerService.create(jobSeeker);
        assertNotNull(created);
    }

    @Test
    @Order(2)
    void read() {
        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());
        assertNotNull(saved);

        JobSeeker found = jobSeekerService.read(saved.getUserId());
        assertNotNull(found);
}

    @Test
    @Order(3)
    void update() {
        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());
        assertNotNull(saved);

        // Using manual setters since @SuperBuilder doesn't have copy method
        JobSeeker updatedJobSeeker = new JobSeeker();
        updatedJobSeeker.setUserId(saved.getUserId());
        updatedJobSeeker.setEmail(saved.getEmail());
        updatedJobSeeker.setPassword(saved.getPassword());
        updatedJobSeeker.setFirstName("Name Updated");
        updatedJobSeeker.setLastName("Surname Updated");
        updatedJobSeeker.setPhoneNumber("0823456789");
        updatedJobSeeker.setLocation("Johannesburg");
        updatedJobSeeker.setHeadline("Senior Java Software Engineer");
        updatedJobSeeker.setSummary("Updated: Senior backend developer with 7 years of experience");

        JobSeeker updated = jobSeekerService.update(updatedJobSeeker);
        assertNotNull(updated);
}

    @Test
    @Order(4)
    @Disabled
    void delete() {
        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());
        assertNotNull(saved);

        boolean deleted = jobSeekerService.delete(saved.getUserId());
        assertTrue(deleted);
}

    @Test
    @Order(5)
    void getAll() {
        jobSeekerService.create(createTestJobSeeker());
        jobSeekerService.create(createTestJobSeeker());

        List<JobSeeker> jobSeekers = jobSeekerService.getAll();
        assertNotNull(jobSeekers);
}

    @Test
    @Order(6)
    void getByEmail() {
        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());
        assertNotNull(saved);

        List<JobSeeker> found = jobSeekerService.getByEmail(saved.getEmail());
        assertNotNull(found);
}

    @Test
    @Order(7)
    void getByEmailNotFound() {
        List<JobSeeker> found = jobSeekerService.getByEmail("doesnotexist@gmail.com");
        assertNotNull(found);
}

    @Test
    @Order(8)
    void createJobSeekerWithAutoGeneratedId() {
        JobSeeker jobSeeker = JobSeekerFactory.createJobSeeker(
                "auto@gmail.com",
                "password123",
                "Auto",
                "Generated",
                "0711111111",
                "Cape Town",
                "Software Developer",
                "Testing UUID generation"
        );

        assertNotNull(jobSeeker);

        JobSeeker created = jobSeekerService.create(jobSeeker);
        assertNotNull(created);
}

}